name: kitchen
dependencies:
- decorator=4.0.4=py35_0
- ipython=4.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- jsonschema=2.4.0=py35_0
- openssl=1.0.2d=0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=7.1.2=py35_0
- python=3.5.0=1
- readline=6.2=2
- setuptools=18.5=py35_0
- simplegeneric=0.8.1=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- traitlets=4.0.0=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - addict==0.4.0
  - anyjson==0.3.3
  - colorama==0.3.3
  - flask==0.10.1
  - futures==3.0.3
  - ipython-genutils==0.1.0
  - itsdangerous==0.24
  - jinja2==2.8
  - markupsafe==0.23
  - mysqlclient==1.3.7
  - six==1.10.0
  - sqlalchemy==1.0.9
  - ujson==1.33
  - werkzeug==0.11.2

